### ISSUE TITLE
The extension is not working with RES infinite scroll. 

### ISSUE THREAD

**Issue by joao44289** [datguysheepy/no-awards-fr#1]
The awards are only being hidden in the first page. When the second page is loaded the awards show up.

![Screenshot (23)](https://user-images.githubusercontent.com/64077887/93073616-16135f00-f67b-11ea-8d00-b6672c48add3.png)

**Comment by datguysheepy** [comment]
Fixed in [v1.1](https://github.com/datguysheepy/no-awards-fr/releases/tag/v1.1)
