### ISSUE TITLE
Suggestion: non-interactable awards

### ISSUE THREAD

**Issue by badken** [datguysheepy/no-awards-fr#5]
This is an outstanding extension, and I use it every day. But... I would actually prefer something slightly different. The awards visuals don't really bother me, it is the fact that they are interactable. I accidentally click on them _all the time_. If the extension only made it so that awards did not react to mouseover or clicks, but were still visible, that would be perfect for me.

Probably not a simple change, so feel free to ignore the suggestion. Thanks for a super useful extension!

**Comment by datguysheepy** [comment]
Hey thanks for this great suggestion, I've decided to add this functionality to the extension and I've just released [new version of the extension](https://github.com/datguysheepy/no-awards-fr/releases/tag/v2.2).
You should see the option to make awards not-interactable in the settings pop-up, so please have a look at it and I hope you'll like it.
